test_that("PRO4AIL produces physically possible values", {
  Refl <- PRO4SAIL()
  expect_true(all(Refl$rdot >= 0))
  expect_true(all(Refl$rsot >= 0))
  expect_true(all(Refl$rddt >= 0))
  expect_true(all(Refl$rsdt >= 0))
  expect_true(all(Refl$fCover >= 0))
  expect_true(all(Refl$abs_dir >= 0))
  expect_true(all(Refl$abs_hem >= 0))
  expect_true(all(Refl$rsdstar >= 0))
  expect_true(all(Refl$rddstar >= 0))
  expect_true(length(Refl$rdot)==length(Refl$rsot))
  expect_true(length(Refl$rdot)==2101)
  expect_true(length(Refl$fCover)==1)
})
