test_that("PRO4AIL produces physically possible values", {
  refl <- prosail()
  expect_true(all(refl$rdot >= 0))
  expect_true(all(refl$rsot >= 0))
  expect_true(all(refl$rddt >= 0))
  expect_true(all(refl$rsdt >= 0))
  expect_true(all(refl$fcover >= 0))
  expect_true(all(refl$abs_dir >= 0))
  expect_true(all(refl$abs_hem >= 0))
  expect_true(all(refl$rsdstar >= 0))
  expect_true(all(refl$rddstar >= 0))
  expect_true(length(refl$rdot)==length(refl$rsot))
  expect_true(length(refl$rdot)==2101)
  expect_true(length(refl$fcover)==1)
})
